name: CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  pull_request:

jobs:
  build-flake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        output: [".#nixosConfigurations.evan-pc.config.system.build.toplevel"]
    steps:
      - name: Maximise build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          build-mount-path: /nix
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Override hackfix nix store perms
        run: sudo chown -R 0 /nix
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: epetousis
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: nix build --accept-flake-config ${{ matrix.output }}
  build-flake-aarch64:
    runs-on: macos-14
    strategy:
      matrix:
        output: [".#darwinConfigurations.evan-mba.system"]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: epetousis
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: nix build --accept-flake-config ${{ matrix.output }}


